# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ZYZ/Desktop/ID_Display/ID_Display.cache/wt [current_project]
set_property parent.project_path C:/Users/ZYZ/Desktop/ID_Display/ID_Display.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/ZYZ/Desktop/ID_Display/ID_Display.srcs/sources_1/new/ID.v
read_xdc C:/Users/ZYZ/Desktop/ID_Display/ID_Display.srcs/constrs_1/new/ID.xdc
set_property used_in_implementation false [get_files C:/Users/ZYZ/Desktop/ID_Display/ID_Display.srcs/constrs_1/new/ID.xdc]

synth_design -top ID -part xc7a35ticpg236-1L
write_checkpoint -noxdef ID.dcp
catch { report_utilization -file ID_utilization_synth.rpt -pb ID_utilization_synth.pb }
