set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN W7 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN W6 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN U8 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN V8 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN U5 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN V5 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN U7 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports add]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports de]
set_property IOSTANDARD LVCMOS33 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports menu]
set_property PACKAGE_PIN V7 [get_ports dp]
set_property PACKAGE_PIN U18 [get_ports menu]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports add]
set_property PACKAGE_PIN R2 [get_ports clr]
set_property PACKAGE_PIN U17 [get_ports de]


set_property PACKAGE_PIN W4 [get_ports {an[3]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]
set_property PACKAGE_PIN U2 [get_ports {an[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports test]
set_property PACKAGE_PIN U16 [get_ports test]


set_property IOSTANDARD LVCMOS33 [get_ports {mode_[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode_[0]}]
set_property PACKAGE_PIN P1 [get_ports {mode_[1]}]
set_property PACKAGE_PIN N3 [get_ports {mode_[2]}]
set_property PACKAGE_PIN L1 [get_ports {mode_[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports alarm_LED]
set_property PACKAGE_PIN U19 [get_ports alarm_LED]
